
import { Screenplay } from './types';

export const CLOSED_LOOP_SCRIPT: Screenplay = {
  title: "闭环 (CLOSED LOOP)",
  author: "标准好莱坞剧本格式转换",
  elements: [
    { id: '1', type: 'TITLE_PAGE', content: '闭环\n\n(CLOSED LOOP)\n\n编剧：AI 实验室\n\n拍摄剧本 (SHOOTING SCRIPT)' },
    
    // SCENE 1
    { id: 's1-h', type: 'SLUGLINE', content: '1. 时空稳定局准备室  2145年7月16日 05:27' },
    { id: 's1-n1', type: 'NOTE', content: '美术指导：房间呈正圆形，墙壁是深灰色哑光金属，镶嵌着不断流动的幽蓝色光纤。中央是一个悬浮的、发出柔和白光的圆形平台（时间锚平台）。房间无明确光源，光线主要由全息屏幕和设备发出。' },
    { id: 's1-n2', type: 'NOTE', content: '关键道具：1. 林夏的腕表：黑色金属表带，复杂微型全息屏。2. 神经阻断枪：流线型，枪口为三个三角形排列的微小电极，附着薄霜。3. 全息屏幕：显示DNA螺旋与星云图结合的数据流。' },
    { id: 's1-sh1', type: 'SHOT', content: '镜头 1 (特写)' },
    { id: 's1-a1', type: 'ACTION', content: '林夏的食指指甲修剪整齐，但指节处有细微的旧伤疤。她用力按下腕表侧面 market的一个蓝色按钮。' },
    { id: 's1-n3', type: 'NOTE', content: '音效：一声低沉有力的“嗡——”声，伴随表盘蓝光瞬间亮起。' },
    { id: 's1-n4', type: 'NOTE', content: 'INSERT：腕表显示“时间锚启动 - 坐标锁定：2023-07-16 09:00:00”' },
    { id: 's1-sh2', type: 'SHOT', content: '镜头 2 (中景->全景)' },
    { id: 's1-a2', type: 'ACTION', content: '镜头从林夏手部拉远，环绕她一周。她站在平台中央，身影挺拔但略显孤独。多个全息屏幕围绕着她缓慢旋转，数据光映在她冷静无波的脸上。' },
    { id: 's1-sh3', type: 'SHOT', content: '镜头 3 (引入冲突)' },
    { id: 's1-a3', type: 'ACTION', content: '一个尖锐的“嘀嘀”蜂鸣声打破寂静。一道金蓝色交织的全息光束从天花板射下，在林夏面前凝聚成局长模糊、威严的影像。' },
    { id: 's1-c1', type: 'CHARACTER', content: '局长 (全息影像)' },
    { id: 's1-d1', type: 'DIALOGUE', content: '特工林夏，最终确认。目标，今天上午 9 点整，滨海市图书馆古籍区。她携带的《时间拓扑学手稿》是最高威胁实体，必须在今天销毁。这是引发 2278 年时间海啸的绝对原点。不容有失。' },
    { id: 's1-sh4', type: 'SHOT', content: '镜头 4 (动作细节)' },
    { id: 's1-a4', type: 'ACTION', content: '林夏听完指令，右手下意识地伸入风衣内侧枪套，手指摩挲着神经阻断枪冰冷的枪身和凝结的冰晶。这个动作熟练而机械。' },
    { id: 's1-sh5', type: 'SHOT', content: '镜头 5 (快速剪辑/闪回)' },
    { id: 's1-a5', type: 'ACTION', content: '快速、失焦、高对比度的黑白画面：一个穿着 20 世纪服饰的男人在雨中惊愕地回头。一个未来装扮的女人在爆炸的火光中伸出手。地面上不同时代的影子倒下。' },
    { id: 's1-sh6', type: 'SHOT', content: '镜头 6 (关键特写)' },
    { id: 's1-a6', type: 'ACTION', content: '林夏面前的一个屏幕自动放大目标档案。照片显示：一位知性、温和的女性，46岁。林夏看到目标面容的瞬间，眼神有一个极其短暂的凝固，随即恢复常态。' },

    // SCENE 2
    { id: 's2-h', type: 'SLUGLINE', content: '2. 滨海市图书馆古籍区  2023年7月16日 09:00:03' },
    { id: 's2-n1', type: 'NOTE', content: '美术指导：深木色高大书架，空气中可见尘埃在光柱中飞舞。温暖的棕色调。' },
    { id: 's2-sh1', type: 'SHOT', content: '镜头 1 (主观视角)' },
    { id: 's2-a1', type: 'ACTION', content: '林夏戴着仿真面具，透过书架缝隙向外窥视。视线扫过安静的阅览区。' },
    { id: 's2-sh2', type: 'SHOT', content: '镜头 2 (跟拍)' },
    { id: 's2-a2', type: 'ACTION', content: '目标（母亲）准时出现。步伐沉稳，走到靠窗桌前，解开深蓝色粗布包裹，露出《时间拓扑学手稿》。' },
    { id: 's2-sh3', type: 'SHOT', content: '镜头 3 (行动)' },
    { id: 's2-a3', type: 'ACTION', content: '林夏如鬼魅般闪出。举枪、瞄准、预压扳机，动作在1秒内完成。' },
    { id: 's2-sh4', type: 'SHOT', content: '镜头 4 (反转)' },
    { id: 's2-a4', type: 'ACTION', content: '母亲没有惊慌。她缓缓抬起头，迎向枪口。脸上露出一丝了然的、带着怜悯的轻笑。' },
    { id: 's2-c1', type: 'CHARACTER', content: '母亲' },
    { id: 's2-d1', type: 'DIALOGUE', content: '这次比上次快了 2 秒，林夏特工。' },
    { id: 's2-sh5', type: 'SHOT', content: '镜头 5 (特写)' },
    { id: 's2-a5', type: 'ACTION', content: '林夏右手猛地一颤。眼神透过面具传递出震惊。' },
    { id: 's2-c2', type: 'CHARACTER', content: '母亲' },
    { id: 's2-d2', type: 'DIALOGUE', content: '别开枪。否则，你会永远困在这个因果闭环里，就像之前的 312 次一样。' },
    { id: 's2-a6', type: 'ACTION', content: '母亲将手稿推向林夏。手稿浮现出发光的蓝色文字，与时空局的任务日志界面一致。' },
    { id: 's2-c3', type: 'CHARACTER', content: '母亲' },
    { id: 's2-d3', type: 'DIALOGUE', content: '从你第一次穿梭过来追杀我开始，这个循环就启动了。每次你都会在扣动扳机前，被手稿第 13 页的内容阻止。' },
    { id: 's2-a7', type: 'ACTION', content: '林夏夺过手稿，翻到第 13 页。上面是她母亲的笔迹。' },
    { id: 's2-c4', type: 'CHARACTER', content: '画外音 (母亲/林夏内心)' },
    { id: 's2-d4', type: 'DIALOGUE', content: '给女儿林夏：当你读到这行字时，请立即前往 1999 年 6 月 12 日的青石巷，坐标...' },

    // SCENE 3
    { id: 's3-h', type: 'SLUGLINE', content: '3. 图书馆崩塌 / 青石巷 (1999)  TRANSITION' },
    { id: 's3-n1', type: 'NOTE', content: '视觉特效：图书馆像像素一样崩塌。林夏用“时空匕首”划开裂缝。' },
    { id: 's3-a1', type: 'ACTION', content: '场景 B：青石巷 - 1999年6月12日' },
    { id: 's3-n2', type: 'NOTE', content: '美术指导：强烈的怀旧感，初夏午后。' },
    { id: 's3-sh1', type: 'SHOT', content: '镜头 1 (远景)' },
    { id: 's3-a2', type: 'ACTION', content: '年轻的母亲（22岁）抱着婴儿走出“圣心福利院”。她一步三回头，极度不舍。' },
    { id: 's3-sh2', type: 'SHOT', content: '镜头 2 (特写)' },
    { id: 's3-a3', type: 'ACTION', content: '林夏手中的复古怀表，刻着“2145.07.16 - 入职纪念”，但表盘日期定格在“2145.07.16”。' },
    { id: 's3-sh3', type: 'SHOT', content: '镜头 3 (闪回)' },
    { id: 's3-a4', type: 'ACTION', content: '回忆画面：局长指着“DNA溯源报告：数据缺失”对年轻的林夏说：“你是战争孤儿，没有家人。”' },
    { id: 's3-c1', type: 'CHARACTER', content: '母亲 (1999)' },
    { id: 's3-d1', type: 'DIALOGUE', content: '时空稳定局建立在一个谎言上... 而我们，是被他们制造出来，又困在自己因果闭环里的实验变量...' },
    { id: 's3-a5', type: 'ACTION', content: '母亲将婴儿交给修女。转身时，露出脖颈后的量子符号刺青。' },
    { id: 's3-sh5', type: 'SHOT', content: '镜头 5 (反应)' },
    { id: 's3-a6', type: 'ACTION', content: '林夏摸向自己锁骨上方。通过玻璃反光，她看到了完全相同的刺青。世界观崩塌。' },
    { id: 's3-end', type: 'TRANSITION', content: 'END OF SCENE 3' },

    // SCENE 4
    { id: 's4-h', type: 'SLUGLINE', content: '4. 纯白无限空间  N/A' },
    { id: 's4-n1', type: 'NOTE', content: '美术指导：纯白色空间，地面如镜面，漂浮着记忆碎片。' },
    { id: 's4-a1', type: 'ACTION', content: '林夏和母亲（中年）面对面。林夏枪口颤抖。' },
    { id: 's4-n2', type: 'NOTE', content: '蒙太奇：局长诡异的微笑。2278年灾难核心是时空局装置。无数个林夏在不同时代瞄准母亲。' },
    { id: 's4-n3', type: 'NOTE', content: '特效：《时间拓扑学手稿》在两人之间燃烧着冰冷的蓝火。进度条：循环验证 332/333。' },
    { id: 's4-c1', type: 'CHARACTER', content: '局长 (画外音)' },
    { id: 's4-d1', type: 'DIALOGUE', content: '第 333 次循环是最终协议。当闭环完成，所有时间旅行者后裔的基因链将同时断裂。' },
    { id: 's4-c2', type: 'CHARACTER', content: '母亲' },
    { id: 's4-d2', type: 'DIALOGUE', content: '开枪吧，孩子。这是终结闭环的唯一方式。我的死亡，是打破这一切的钥匙。' },
    { id: 's4-sh1', type: 'SHOT', content: '镜头 (慢动作)' },
    { id: 's4-a2', type: 'ACTION', content: '母亲上前，握住林夏的手，将枪口调转对准自己的心脏。林夏瞳孔猛缩，但母亲力量巨大。' },
    { id: 's4-a3', type: 'ACTION', content: '母亲推动林夏的手指，扣动了扳机。' },
    { id: 's4-n4', type: 'NOTE', content: '画面：纯白光芒淹没一切。' },
    { id: 's4-end', type: 'TRANSITION', content: 'END OF SCENE 4' },

    // SCENE 5
    { id: 's5-h', type: 'SLUGLINE', content: '5. 时空局医疗舱 / 青石巷  2145 / 1999' },
    { id: 's5-a1', type: 'ACTION', content: '场景 A：时空稳定局医疗舱' },
    { id: 's5-a2', type: 'ACTION', content: '林夏醒来。刺青已消失。局长影像出现，祝贺她完成任务。' },
    { id: 's5-a3', type: 'ACTION', content: '林夏面无表情，但眼底闪过彻骨的冰冷和嘲讽。她握紧拳头，指甲陷入掌心。' },
    { id: 's5-a4', type: 'ACTION', content: '场景 B：青石巷 (1999年) - 未被观测的时间线' },
    { id: 's5-a5', type: 'ACTION', content: '夕阳。年轻的母亲没有离开，她抱着婴儿站在槐树下，微笑。' },
    { id: 's5-sh1', type: 'SHOT', content: '特写' },
    { id: 's5-a6', type: 'ACTION', content: '婴儿腕间系着半片烧焦的手稿残页。上面是母亲新写的字迹：' },
    { id: 's5-n1', type: 'NOTE', content: '“给女儿林夏：当你开启第 333 次循环时... ...反击... ...”' },
    { id: 's5-t1', type: 'TRANSITION', content: 'FADE TO BLACK.' },
    { id: 's5-n2', type: 'NOTE', content: '全剧终' },
    { id: 's5-end', type: 'TRANSITION', content: 'END OF SCENE 5' }
  ]
};
